# Generated by Django 4.2.7 on 2024-04-05 12:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=11, verbose_name='place')),
                ('start_time', models.TimeField(verbose_name='start time')),
                ('action', models.CharField(max_length=22, verbose_name='action')),
                ('nice_habit', models.BooleanField(default=False, verbose_name='nice_habit')),
                ('periodicity', models.PositiveIntegerField(default=1)),
                ('reward', models.CharField(blank=True, max_length=33, null=True)),
                ('time_to_complete', models.DurationField(db_comment='ISO 8601 PT?S', default='PT120S')),
                ('is_public', models.BooleanField(default=False)),
                ('related_habit', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='habits.habit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'habit',
                'verbose_name_plural': 'habits',
            },
        ),
    ]
