# Generated by Django 4.2.7 on 2024-04-05 12:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0002_alter_habit_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='time_to_complete',
            field=models.DurationField(db_comment='ISO 8601 PT?S', default=datetime.timedelta(seconds=120)),
        ),
    ]
